name: Build
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v16
      - name: Build
        run: nix build
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: bech32_${{ runner.os }}_${{ runner.arch }}
          path: ./result/bin/bech32
